/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.14
 * Generated at: 2023-11-06 09:34:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Modelo.Alumno;
import java.util.ArrayList;

public final class alumnos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Modelo.Alumno");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

//REcuperar alumnos que vienen del controlador
ArrayList<Alumno> alumnos = (ArrayList<Alumno>) request.getAttribute("alumnos");
if(alumnos==null){
	response.sendRedirect("ControladorAlumnos");
}
//Obtener el mensaje que viene del controlador
String mensaje = (String) request.getAttribute("mensaje");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"ISO-8859-1\">\r\n");
      out.write("	<title>Alumnos</title>\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\"crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("		\r\n");
      out.write("		<h3 style=\"text-align: center;\">GESTION DE ALUMNOS</h3>\r\n");
      out.write("	</header>\r\n");
      out.write("	\r\n");
      out.write("	<section>\r\n");
      out.write("		<div class=\"container mt-3 p-3 w-100 border\">\r\n");
      out.write("			<form action=\"ControladorAlumnos\" class=\"form-inline\" method=\"post\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col\">\r\n");
      out.write("						<label>DNI</label>\r\n");
      out.write("						<input type=\"text\" name=\"dni\" required=\"required\" class=\"form-control form-control-sm\"/>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col\">\r\n");
      out.write("						<label>Nombre</label>\r\n");
      out.write("						<input type=\"text\" name=\"nombre\" required=\"required\"  class=\"form-control form-control-sm\"/>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col\">\r\n");
      out.write("						<label>Num. Expediente</label>\r\n");
      out.write("						<input type=\"number\" name=\"exp\" required=\"required\"  class=\"form-control form-control-sm\"/>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col\">\r\n");
      out.write("						<label>Fecha Nacimiento</label>\r\n");
      out.write("						<input type=\"date\" name=\"fecha\" required=\"required\"  class=\"form-control form-control-sm\"/>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col\">\r\n");
      out.write("						<label>Estatura</label>\r\n");
      out.write("						<input type=\"number\" name=\"estatura\"  required=\"required\"  class=\"form-control form-control-sm\"/>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col\">\r\n");
      out.write("						<br/>\r\n");
      out.write("						<button type=\"submit\" name=\"accion\" value=\"crear\" \r\n");
      out.write("						class=\"btn btn-outline-dark\">Crear</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<section>\r\n");
      out.write("\r\n");
      out.write("			");

			if(mensaje!=null){
				out.println("<div class='container mt-1 p-1 w-100 border'>");
				out.println("<h6 class='text-danger'>"+mensaje+"</h6></div>");	
			}
			
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	</section>\r\n");
      out.write("	<section>\r\n");
      out.write("	<div class=\"container mt-3 p-3 w-100 border\">\r\n");
      out.write("		<!--  pintar alumnos en una tabla -->\r\n");
      out.write("		<form action=\"ControladorAlumnos\" class=\"form-inline\" method=\"post\">\r\n");
      out.write("		<table class=\"table table-striped\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>DNI</th>\r\n");
      out.write("				<th>Nombre</th>\r\n");
      out.write("				<th>Fecha Nacimiento</th>\r\n");
      out.write("				<th>Num. Expediente</th>\r\n");
      out.write("				<th>Estatura</th>\r\n");
      out.write("				<th>Activo</th>\r\n");
      out.write("				<th>Acciones</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");

			if(alumnos!=null){
				for(Alumno a : alumnos){
					out.println("<tr>");
					out.println("<td>"+a.getDni()+"</td>");
					out.println("<td>"+a.getNombre()+"</td>");
					out.println("<td>"+a.getFechaN()+"</td>");
					out.println("<td>"+a.getNumExp()+"</td>");
					out.println("<td>"+a.getEstatura()+"</td>");
					out.println("<td>"+a.isActivo()+"</td>");
					out.println("<td>"+
					"<button type='submit' name='accion' value='baja/"+a.getDni()+"' class='btn btn-outline-primary'>Baja</button>"+
					"<button type='submit' name='accion' value='borrar/"+a.getDni()+"' class='btn btn-outline-danger'>Borrar</button>"+					
							"</td>");
					out.println("</tr>");
				}
			}
			
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		</table>\r\n");
      out.write("		</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	\r\n");
      out.write("	<footer>\r\n");
      out.write("	</footer>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
